apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-session-hazelcast-deployment
  labels:
    app: express-session-hazelcast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-session-hazelcast
  template:
    metadata:
      labels:
        app: express-session-hazelcast
    spec:
      containers:
        - name: express-session-hazelcast
          image: huseyinbabal/express-session-hazelcast
          imagePullPolicy: Always
          env:
            - name: HZ_STORE_ENABLED
              value: "true"
            - name: HZ_CLOUD_DISCOVERY_TOKEN
              value: "<discovery_token>"
            - name: HZ_CLOUD_GROUP_NAME
              value: "<cluster_name>"
            - name: HZ_CLOUD_PASSWORD
              value: "<cluster_password>"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-session-hazelcast-service
spec:
  selector:
    app: express-session-hazelcast
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
